version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql11/data

volumes:
  db:
    driver: local
